language: php

php:
  - 5.4

install:
  - composer install

branches:
  only:
    - master
    
script: phpunit

after_success:
  - "curl http://travis-ci:LZzhkv7lVf5Yc@162.242.230.200/deploy/octopush.php"
